### ISSUE TITLE
``can't cd /usr/src/app/lims/node_modules/npm`` error, when building wih docker-compose up

### ISSUE THREAD

**Issue by Zulko** [GETLIMS/LIMS-Frontend#1]
Hi there,
Is "docker-compose up" already supposed to work ? I am trying to build the project using ``docker-compose up`` int the Backend folder:

```
LIMS/
├── LIMS-Backend/  <- where I run the command.
└── LIMS-Frontend/
```

When it is building the frontend, I get this error, which makes the whole build fail and stop:

```
Step 16 : RUN cd $(npm root)/npm   && npm install fs-extra   && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs.move/ ./lib/utils/rename.js
 ---> Running in f66c84daecee
/bin/sh: 1: cd: can't cd to /usr/src/app/lims/node_modules/npm
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c cd $(npm root)/npm   && npm install fs-extra   && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs.move/ ./lib/utils/rename.js' returned a non-zero code: 2
```

Any idea how to fix this ?

Thanks !

**Comment by tjomasc** [comment]
This seems to be a massive issue with NPM and the fs-extra package. There are manual workarounds but thanks to an overly complicted depenency tree the issues keeps reappearing. You can avoid having to build everything from scratch by using the docker-compose package from here: https://github.com/LeafLIMS/docker. This will pull pre-built images down that don't require NPM and should load far more quickly. I'll also update the documentation which is old enough to not have a section on this present.
