### ISSUE TITLE
Trying to make changes to frontend-code, not sure where the /src files LeafLIMS is deployed

### ISSUE THREAD

**Issue by sqilz** [GETLIMS/LIMS-Frontend#5]
Does /src get removed when deploying? also `au run --watch` doesn't seem to work it returns a json in terminal and quits, am I supposed to run a local server when trying to run it?   Also how would I make/apply changes to already deployed app as I can?

Also i'm getting this feeling that what is in this repository is behind the 3.2.1 image on docker, am I wrong?

Also is there any other way I could contact @tjomasc which isn't here to ask for advice instead of making issue tickers (which is not ideal)

I would be interested in carrying on with development of LeafLIMS to improve my skills

**Comment by sqilz** [comment]
Also when trying to build i get `Error: File not found with singular glob: *\LIMS-Frontend\third_party\semantic-ui\semantic.min.css`

**Comment by sqilz** [comment]
Okay i got it to run, but how do I log in on localhost without running the backend

**Comment by tjomasc** [comment]
Hi there,

The frontend you have downloaded will not work without running the backend - it is just the user interface for displaying data from the backend REST API. You're correct that the LIMS-Frontend image on Docker is based on the compiled code from this repository. Leaf LIMS is designed to be run primarily through Docker, check out the main [Leaf LIMS repository](https://github.com/LeafLIMS/LeafLIMS) for how that works.

If you are interested in developing Leaf LIMS I suggest that you familiarise yourself with [Aurelia](https://aurelia.io/docs/) and [Django Rest Framework](https://www.django-rest-framework.org/) as these are key to how Leaf LIMS works. Instructions on how to set up the system for development can be found [here](https://leaflims.github.io/docs/setup/index.html), though it's not as comprehensive as I would like.

If it's not a bug report (please still post them here, it helps others who are contributing) you can contact me at thomas.craig@liverpool.ac.uk. I'll do my best to answer any questions you have :)
