### ISSUE TITLE
Submodules "aurelia-route-mapper" and "semantic-ui" not downloaded when cloned with --recursive

### ISSUE THREAD

**Issue by frba** [GETLIMS/LIMS-Frontend#6]
I run git clone --recursive https://github.com/LeafLIMS/LIMS-Frontend.git
But I got the same error as seen in here: https://github.com/LeafLIMS/LIMS-Frontend/issues/5
Error: File not found with singular glob: *\LIMS-Frontend\third_party\semantic-ui\semantic.min.css

The folders "aurelia-route-mapper" and "semantic-ui" are empty. What files should be in these folders?

I'm planning to do some modifications in the frontend and backend to adequate the leaflims to our lab's necessities.

**Comment by tjomasc** [comment]
Sorry about that, the submodule definitions where messed up. I've hopefully corrected it so you should be able to clone the repository now.
